### ISSUE TITLE
２次元リスト初期化のところ、内包表記のインデックスが逆

### ISSUE THREAD

**Issue by Naohiro2g** [chokkan/python#2]

**Comment by Naohiro2g** [comment]
https://github.com/chokkan/python/blob/0322e0c42ab86635d869bdd816149f0dceda9f3a/06list.ipynb#L2079

`b = [[0 for i in range(10)] for j in range(10)]`

些細なことですが、インデックスiとjを入れ替えたほうが良いのではないでしょうか？　x, yとの対応で考えると。

あと、`b = [[0 for j in range(10)] for i in range(8)]`　など、正方形でない形にしておいたほうが勘違いが避けられるかと思います。これで、b[8][10]のリストが初期化されます。

**Comment by chokkan** [comment]
大変遅くなりまして申し訳ありません。おっしゃる通りだと思いますので、`i`と`j`を入れ替えました。正方形ではない方が無難というご指摘もその通りなのですが、九九の掛け算表を題材にしてしまったので、とりあえず正方形で進めたいと思います
。

**Comment by Naohiro2g** [comment]
ありがとうございます。
参考にさせてもらっています。Google Colabが18歳未満は使えなくなってしまったのは残念でしたが、VS CodeのJupyterがとても使いやすくなったので、小中高の生徒たちと一緒に利用しています。
